//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc1_student.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcdbEntities2 : DbContext
    {
        public MvcdbEntities2()
            : base("name=MvcdbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb1_cls> tb1_cls { get; set; }
        public virtual DbSet<tb1_std> tb1_std { get; set; }
        public virtual DbSet<tb1_sub> tb1_sub { get; set; }

        public System.Data.Entity.DbSet<Mvc1_student.Models.studentViewModel> studentViewModels { get; set; }
    }
}
