//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc1_student.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb1_std
    {
        public int std_id { get; set; }

        [RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$", ErrorMessage = "Special Characters are  not  allowed.")]
        public string std_name { get; set; }
        public string std_add { get; set; }

         [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Phone No should be 10 digit")]
        public string std_phn { get; set; }
        public Nullable<int> std_clsid { get; set; }
        public Nullable<int> std_subid { get; set; }
    
        public virtual tb1_cls tb1_cls { get; set; }
        public virtual tb1_sub tb1_sub { get; set; }
    }
}
